# Generated by Django 5.0 on 2023-12-17 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.books'),
            preserve_default=False,
        ),
    ]
