// import 'package:flutter/material.dart';
// import 'package:bookify/screens/login.dart';

// void main() {
//   runApp(const MyApp());
// }

// class MyApp extends StatelessWidget {
//   const MyApp({super.key});

//   // This widget is the root of your application.
//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       title: 'Flutter Demo',
//       theme: ThemeData(
//         // This is the theme of your application.
//         //
//         // TRY THIS: Try running your application with "flutter run". You'll see
//         // the application has a blue toolbar. Then, without quitting the app,
//         // try changing the seedColor in the colorScheme below to Colors.green
//         // and then invoke "hot reload" (save your changes or press the "hot
//         // reload" button in a Flutter-supported IDE, or press "r" if you used
//         // the command line to start the app).
//         //
//         // Notice that the counter didn't reset back to zero; the application
//         // state is not lost during the reload. To reset the state, use hot
//         // restart instead.
//         //
//         // This works for code too, not just values: Most code changes can be
//         // tested with just a hot reload.
//         colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
//         useMaterial3: true,
//       ),
//       home: const LoginPage(),
//     );
//   }
// }


import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Bookreview(),
        ]),
      ),
    );
  }
}

class Bookreview extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 1,
                top: -38,
                child: Container(
                  width: 393,
                  height: 244,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.00, -1.00),
                      end: Alignment(0, 1),
                      colors: [Color(0xFF71C3F7), Color(0xFFC1FCFE)],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(40),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 342,
                top: 56,
                child: Container(
                  width: 32,
                  height: 32,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(children: [
                  ,
                  ]),
                ),
              ),
              Positioned(
                left: 25,
                top: 55,
                child: Container(
                  width: 225,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 38,
                        top: 5,
                        child: SizedBox(
                          width: 187,
                          child: Text(
                            'Hello User! ',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 20,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w600,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 34,
                          height: 34,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Container(
                                width: 31.17,
                                height: 31.17,
                                child: Stack(children: [
                                ,
                                ]),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 25,
                top: 146,
                child: Container(
                  width: 351,
                  height: 41.42,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 20,
                        top: 9,
                        child: SizedBox(
                          width: 190,
                          child: Text(
                            'Search',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 20,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w100,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 308,
                        top: 0,
                        child: Container(
                          width: 37,
                          height: 37,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(children: [
                          ,
                          ]),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 25,
                top: 248,
                child: Container(
                  height: 539,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.end,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 344,
                        height: 1343,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 150,
                                height: 199,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 150,
                                        height: 199,
                                        decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                      ),
                                    ),
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 150,
                                        height: 211,
                                        decoration: BoxDecoration(
                                          image: DecorationImage(
                                            image: NetworkImage("https://via.placeholder.com/150x211"),
                                            fit: BoxFit.fill,
                                          ),
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 0,
                              top: 230,
                              child: Container(
                                width: 150,
                                height: 199,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 150,
                                        height: 199,
                                        decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                      ),
                                    ),
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 141,
                                        height: 199,
                                        decoration: BoxDecoration(
                                          image: DecorationImage(
                                            image: NetworkImage("https://via.placeholder.com/141x199"),
                                            fit: BoxFit.fill,
                                          ),
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 194,
                              top: 0,
                              child: Container(
                                width: 150,
                                height: 199,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 150,
                                        height: 199,
                                        decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                      ),
                                    ),
                                    Positioned(
                                      left: -10,
                                      top: -27,
                                      child: Container(
                                        width: 169,
                                        height: 241,
                                        decoration: BoxDecoration(
                                          image: DecorationImage(
                                            image: NetworkImage("https://via.placeholder.com/169x241"),
                                            fit: BoxFit.fill,
                                          ),
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 194,
                              top: 230,
                              child: Container(
                                width: 150,
                                height: 199,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 150,
                                        height: 199,
                                        decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                      ),
                                    ),
                                    Positioned(
                                      left: 4,
                                      top: 0,
                                      child: Container(
                                        width: 151,
                                        height: 193,
                                        decoration: BoxDecoration(
                                          image: DecorationImage(
                                            image: NetworkImage("https://via.placeholder.com/151x193"),
                                            fit: BoxFit.fill,
                                          ),
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 0,
                              top: 457,
                              child: Container(
                                width: 150,
                                height: 199,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 150,
                                        height: 199,
                                        decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                      ),
                                    ),
                                    Positioned(
                                      left: 0,
                                      top: -11,
                                      child: Container(
                                        width: 208,
                                        height: 319,
                                        decoration: BoxDecoration(
                                          image: DecorationImage(
                                            image: NetworkImage("https://via.placeholder.com/208x319"),
                                            fit: BoxFit.fill,
                                          ),
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 194,
                              top: 457,
                              child: Container(
                                width: 150,
                                height: 199,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 150,
                                        height: 199,
                                        decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                      ),
                                    ),
                                    Positioned(
                                      left: 0,
                                      top: -17,
                                      child: Container(
                                        width: 153,
                                        height: 233,
                                        decoration: BoxDecoration(
                                          image: DecorationImage(
                                            image: NetworkImage("https://via.placeholder.com/153x233"),
                                            fit: BoxFit.fill,
                                          ),
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 0,
                              top: 687,
                              child: Container(
                                width: 150,
                                height: 199,
                                decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                              ),
                            ),
                            Positioned(
                              left: 194,
                              top: 687,
                              child: Container(
                                width: 150,
                                height: 199,
                                decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                              ),
                            ),
                            Positioned(
                              left: 0,
                              top: 917,
                              child: Container(
                                width: 150,
                                height: 199,
                                decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                              ),
                            ),
                            Positioned(
                              left: 194,
                              top: 917,
                              child: Container(
                                width: 150,
                                height: 199,
                                decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                              ),
                            ),
                            Positioned(
                              left: 0,
                              top: 687,
                              child: Container(
                                width: 150,
                                height: 199,
                                decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                              ),
                            ),
                            Positioned(
                              left: 194,
                              top: 687,
                              child: Container(
                                width: 150,
                                height: 199,
                                decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                              ),
                            ),
                            Positioned(
                              left: 0,
                              top: 1144,
                              child: Container(
                                width: 150,
                                height: 199,
                                decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                              ),
                            ),
                            Positioned(
                              left: 194,
                              top: 1144,
                              child: Container(
                                width: 150,
                                height: 199,
                                decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: -10,
                top: 769,
                child: Container(
                  width: 410,
                  height: 85,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 19,
                        child: Container(
                          width: 410,
                          height: 66,
                          decoration: BoxDecoration(
                            color: Colors.white,
                            boxShadow: [
                              BoxShadow(
                                color: Color(0x3F000000),
                                blurRadius: 20,
                                offset: Offset(0, -10),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 169,
                        top: 0,
                        child: Container(
                          width: 76,
                          height: 76,
                          decoration: ShapeDecoration(
                            gradient: LinearGradient(
                              begin: Alignment(0.00, -1.00),
                              end: Alignment(0, 1),
                              colors: [Color(0xFF52B9CB), Color(0xFFC1FCFE)],
                            ),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 182,
                        top: 12,
                        child: Container(
                          width: 51,
                          height: 51,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(children: [
                          ,
                          ]),
                        ),
                      ),
                      Positioned(
                        left: 354,
                        top: 40,
                        child: Container(
                          width: 30,
                          height: 30,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(children: [
                          ,
                          ]),
                        ),
                      ),
                      Positioned(
                        left: 27,
                        top: 36,
                        child: Container(
                          width: 37,
                          height: 37,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(children: [
                          ,
                          ]),
                        ),
                      ),
                      Positioned(
                        left: 107,
                        top: 36,
                        child: Container(
                          width: 32,
                          height: 32,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(children: [
                          ,
                          ]),
                        ),
                      ),
                      Positioned(
                        left: 277,
                        top: 40,
                        child: Container(
                          width: 33,
                          height: 33,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(children: [
                          ,
                          ]),
                        ),
                      ),
                      Positioned(
                        left: 21,
                        top: 28,
                        child: Opacity(
                          opacity: 0.80,
                          child: Container(
                            width: 50,
                            height: 50,
                            decoration: ShapeDecoration(
                              color: Color(0xCCD9D9D9),
                              shape: OvalBorder(),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 63,
                top: 89,
                child: SizedBox(
                  width: 187,
                  child: Text(
                    'BookReview & Fav',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w600,
                      height: 0,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}