# Generated by Django 4.2.7 on 2023-12-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdonation', '0011_data_donasi1_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_donasi1',
            name='coin_reedem',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
