# Generated by Django 4.2.6 on 2023-12-13 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookdonation', '0012_data_donasi1_coin_reedem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_donasi1',
            name='coin_reedem',
        ),
        migrations.CreateModel(
            name='poin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_reedem', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
