# Generated by Django 4.2.6 on 2023-12-13 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookdonation', '0013_remove_data_donasi1_coin_reedem_poin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poin',
            name='coin_reedem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
